name: Runner
on:
  workflow_dispatch:
jobs:
  work_runner:
    runs-on: ubuntu-latest
    steps:
      - name: System update
        run: |
         sudo apt-get update && sudo apt-get upgrade
         sudo apt-get install cabextract wimtools chntpw genisoimage

      - name: Checkout
        uses: actions/checkout@v3.0.1

      - name: Run script
        run: |
          chmod +x *.sh 
          ./uup_download_apps.sh
          ls -al

      - name: Upload WSA to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 22621.1_PROFESSIONAL_X64_EN-US.ISO
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: 22621.819
