name: Runner
on:
  workflow_dispatch:
jobs:
  work_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1

      - name: Run script
        run: |
          cd potential-lamp
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install cabextract wimtools chntpw genisoimage
          chmod +x *.sh 
          ./uup_download_linux.sh
          ls -al
